### PR TITLE
Display equations correctly

### LINKED ISSUE #40: Equations in Step11 got messed up.
Correctly displaying at Step12 -> copy from there where applicable. 
grafik

### PR DESCRIPTION
**Pull request by mesnardo**
Fix #40 

Use Latex split environment.
Remove line breaks to display equation correctly.

You can view the modified notebooks with Nbviewer to check the equations:

* Step 7: [before](https://nbviewer.jupyter.org/github/barbagroup/CFDPython/blob/master/lessons/09_Step_7.ipynb) and [after](https://nbviewer.jupyter.org/github/mesnardo/CFDPython/blob/display-equations/lessons/09_Step_7.ipynb);
* Step 8: [before](https://nbviewer.jupyter.org/github/barbagroup/CFDPython/blob/master/lessons/10_Step_8.ipynb) and [after](https://nbviewer.jupyter.org/github/mesnardo/CFDPython/blob/display-equations/lessons/10_Step_8.ipynb);
* Step 10: [before](https://nbviewer.jupyter.org/github/barbagroup/CFDPython/blob/master/lessons/13_Step_10.ipynb) and [after](https://nbviewer.jupyter.org/github/mesnardo/CFDPython/blob/display-equations/lessons/13_Step_10.ipynb);
* Step 11: [before](https://nbviewer.jupyter.org/github/barbagroup/CFDPython/blob/master/lessons/15_Step_11.ipynb) and [after](https://nbviewer.jupyter.org/github/mesnardo/CFDPython/blob/display-equations/lessons/15_Step_11.ipynb);
* Step 12: [before](https://nbviewer.jupyter.org/github/barbagroup/CFDPython/blob/master/lessons/16_Step_12.ipynb) and [after](https://nbviewer.jupyter.org/github/mesnardo/CFDPython/blob/display-equations/lessons/16_Step_12.ipynb).

### CODE REVIEW

**Comment by labarba** [comment]
@mesnardo Following your links, I don't see any difference between "before" and "after"—confused.

**Comment by mesnardo** [comment]
@labarba, sorry for the confusion, I should give more details.

In Step 7, I replaced `align` latex environment with `split`, a good one to split a single equation over multiple lines. (In Nbviewer, there should be no difference.)

In Step 8, I added the `split` environment in several locations to split single equations, instead of using `$$...$$` multiple times. (Again, in Nbviewer, there should be no difference.)

In Step 10, I removed the equation numbering (`eqnarray` -> `eqnarray*`). (In Nbviewer, the equation number should not appear anymore--it was not needed.)

In Step 11, I replaced `eqnarray` latex environment by `split` to split single equations over multiple lines. I also used `split` environment instead of multiple `$$...$$` in several locations (this was messing up the display of one equation, which has been reported in issue #40). (In Nbviewer, the equation numbers are removed and all equations are displayed correctly.)

In Step 12, I have done the same changes than in step 11, for consistency. (In Nbviewer, the equation numbers are removed.)

**Comment by gforsyth** [comment]
@mesnardo -- is this ready to go in?

**Comment by gforsyth** [comment]
Hey @mesnardo -- can you merge or rebase against master to clear up the conflicts?  Then this can go in.

**Comment by mesnardo** [comment]
@gforsyth, I rebased against master.

**Comment by gforsyth** [comment]
Awesome, thanks @mesnardo !

**Pull request merged**
